### ISSUE TITLE
Streamcloud.eu removed

### ISSUE THREAD

**Issue by Lynx187** [Eldorados/script.module.urlresolver#251]
Why was the resolver streamcloud.eu removed with this commit: https://github.com/Eldorados/script.module.urlresolver/commit/f91afaa281837c80e5e37c27e78d6751fb4fe5ce

Yes, the hoster had some problems recently, but it is still working.

**Comment by Eldorados** [comment]
They must have been down during the period that we were verifying the hosts, I'll pop it back in

**Comment by tknorris** [comment]
The best information I can find says that they haven't worked in over a year and hoster search sites show no new videos since January of 2014...Can you find some examples more recently that either work or have worked?

**Comment by Lynx187** [comment]
This one for example is definitly working from my location : http://streamcloud.eu/31girj871eb7
For more examples you could check http://www.burning-serie.es

**Comment by tknorris** [comment]
So, that first link comes up as a 404 Not Found for me. Maybe someone else can test it? Perhaps it's geo blocked....

Also, that burning-serie.es site comes up as a dummy/for sale site....

**Comment by Eldorados** [comment]
The link works for me                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                                         From: tknorrisSent: Wednesday, January 28, 2015 12:58 PMTo: Eldorados/script.module.urlresolverReply To: Eldorados/script.module.urlresolverCc: EldoradosSubject: Re: [script.module.urlresolver] Streamcloud.eu removed (#251)So, that first link comes up as a 404 Not Found for me. Maybe someone else can test it? Perhaps it's geo blocked....

Also, that burning-serie.es site comes up as a dummy/for sale site....

—Reply to this email directly or view it on GitHub.

**Comment by tknorris** [comment]
So, a quick survey seems to confirm that streamcloud is blocked in the U.S. Everyone in the U.S. gets a 404, but outside the links work fine.

**Comment by Lynx187** [comment]
Yes that was one "e" too much, I ment https://www.burning-seri.es/
