### ISSUE TITLE
error_logo not in global space

### ISSUE THREAD

**Issue by Joe136** [Eldorados/script.module.urlresolver#254]
Hi,

I have seen that some resolvers uses the variable *error_logo* but doesn't define it.

Example:
Resolver *180upload* has the definition ```error_logo = os.path.join(...```
Resolver *bayfiles* hasn't, but using it ```common.addon.show_small_popup(..., image=error_logo)```

I have seen this for *bayfiles*, *crunchyroll* and *rpnet*, but there could be more.

Best Regards
Joe

**Comment by tknorris** [comment]
We are in the process of slowly stripping out that and the pop-ups in the resolvers.

**Comment by Eldorados** [comment]
Just fixed the ones mentioned, thanks as those would have cause another exception if the code was called

**Comment by Joe136** [comment]
I have grep'ed for it and these resolvers have the same problem:
```grep -LEe '^[ ]*error_logo' $(grep -l error_logo -R .)```
*rapidvideo.py* | *tubeplus.py* | *veoh.py* | *videobb.py* | *xvidstage.py*

PS: ```grep -l error_logo -R .``` speeds up the stripping process ;)
