### ISSUE TITLE
Two issues w/ the domain logic

### ISSUE THREAD

**Issue by tknorris** [Eldorados/script.module.urlresolver#257]
1) Host validation doesn't work anymore when the host is only supported by a universal resolver. This was a problem for a while in the old code but was fixed recently. It's not clear to me how to fix it in the new code.
2) It used to be true that if an HMF returned true when instantiated, it could be resolved, That's no longer true as now it just means the domain matched. Both 1CH and SALTS depend on this logic.

**Comment by tknorris** [comment]
A good example of this is filefactory.com. This is only supported by the debrid resolvers and there is no dedicated resolver. Due to that, the HMF returns False when using host validation.

**Comment by tknorris** [comment]
@VioletRed FYI

**Comment by tknorris** [comment]
OK, so the problem is is before __nonzero__ returned True is there were resolvers, but now it only returns True if the url is valid. When doing host validation, the url is rarely/never valid.

**Comment by tknorris** [comment]
I submitted PR #258 I think that fixes problem 1. I'm not sure what to do (if anything?) about the 2nd problem yet.

**Comment by VioletRed** [comment]
I'm trying to understand problem 2. Could you point at the relevant parts in 1channel or some test case?

It could be possible to call self.valid_url() at __init__ to match the original behavior, but it would be better to check against an actual test case.

**Comment by tknorris** [comment]
closing this since #258 fix it.
