### ISSUE TITLE
Please could you add Uptostream.

### ISSUE THREAD

**Issue by Sanjjay** [Eldorados/script.module.urlresolver#262]
Please could you add Uptobox links which will convert to Uptostream in URL resolver.

This may help https://github.com/LordVenom/venom-xbmc-addons/blob/master/plugin.video.vstream/resources/hosters/uptostream.py 

http://uptobox.com/agstu36h7imf also http://uptostream.com/agstu36h7imf

Also venoms got few more other sharing websites which URL resolver doesn't have and if they can be added would be great.

**Comment by smokdpi** [comment]
Pull #333 includes this
