### ISSUE TITLE
Allmyvideos not work

### ISSUE THREAD

**Issue by pikomule** [Eldorados/script.module.urlresolver#282]
18:22:02 T:1400  NOTICE: -->Python Interpreter Initialized<--
18:22:02 T:1400  NOTICE: CommonFunctions-2.5.1
18:22:02 T:1400  NOTICE: http://allmyvideos.net/mo8orxuwexcw
18:22:02 T:1400  NOTICE: common resolver
18:22:02 T:1400  NOTICE: allmyvideos.net
18:22:02 T:1400  NOTICE: URLResolver: Initializing URLResolver version: 2.8.0
18:22:06 T:5664  NOTICE: DVDPlayer: Opening: http://d4416.allmyvideos.net/d/yomidjeuyq5dh6lnw7ejx265emjzcmifkhr22ooswlwkqnkb47a43ligd2hc3gi/video.mp4?v2|User-Agent=Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:30.0) Gecko/20100101 Firefox/30.0
18:22:06 T:5664 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
18:22:06 T:5664  NOTICE: DXVA::CProcessorHD::PreInit - The Direct3d device doesn't support DXVA-HD.
18:22:06 T:5664  NOTICE: CWinRenderer::Preinit - could not init DXVA-HD processor - skipping
18:22:06 T:3824  NOTICE: Thread DVDPlayer start, auto delete: false
18:22:06 T:3824  NOTICE: Creating InputStream
18:22:06 T:3824  NOTICE: Creating Demuxer
18:22:06 T:2548  NOTICE: Thread FileCache start, auto delete: false
18:22:36 T:3824   ERROR: CDVDDemuxFFmpeg::Open - Error, could not open file http://d4416.allmyvideos.net/d/yomidjeuyq5dh6lnw7ejx265emjzcmifkhr22ooswlwkqnkb47a43ligd2hc3gi/video.mp4?v2
18:22:37 T:3824   ERROR: CDVDPlayer::OpenDemuxStream - Error creating demuxer
18:22:37 T:3824  NOTICE: CDVDPlayer::OnExit()
18:22:37 T:5664   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.live.streamspro161/?url=http%3A%2F%2Fallmyvideos.net%2Fmo8orxuwexcw&mode=19]
18:22:37 T:5664  NOTICE: CDVDPlayer::CloseFile()
18:22:37 T:5664  NOTICE: DVDPlayer: waiting for threads to exit
18:22:37 T:5664  NOTICE: DVDPlayer: finished waiting
18:22:37 T:5664  NOTICE: CDVDPlayer::CloseFile()
18:22:37 T:5664  NOTICE: DVDPlayer: waiting for threads to exit
18:22:37 T:5664  NOTICE: DVDPlayer: finished waiting
18:22:37 T:4708  NOTICE: Thread JobWorker start, auto delete: true

**Comment by tknorris** [comment]
FYI, I just tested the resolver on the current github code and it works fine.

**Comment by pikomule** [comment]
LivestreamsPro not work in 1.6.1.

Playedto, streamingto, etc if they work

**Comment by Eldorados** [comment]
Latest version of urlresolver is 2.8.0                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: pikomuleSent: Friday, March 27, 2015 9:15 AMTo: Eldorados/script.module.urlresolverReply To: Eldorados/script.module.urlresolverSubject: Re: [script.module.urlresolver] Allmyvideos not work (#282)LivestreamsPro not work in 1.6.1.

Playedto, streamingto, etc if they work

—Reply to this email directly or view it on GitHub.

**Comment by pikomule** [comment]
Look at the log of the first message, I'm using the verion 2.8.0

18:22:02 T:1400 NOTICE: URLResolver: Initializing URLResolver version: 2.8.0

**Comment by Eldorados** [comment]
You just mentioned 1.6.1

Btw, your log shows the resolver working fine as it retrieved the final
url, it just failed to play - it waited 30 seconds and the file stream
didn't start, likely the host is just responding slowly

**Comment by pikomule** [comment]
I mean LivestreamsPro 1.6.1. I use it on KODI 14.1 and 14.2.

**Comment by pikomule** [comment]
Log in Android (log first message in Windows 7):

16:31:32 T:1947734000  NOTICE: URLResolver: Initializing URLResolver version: 2.8.0
16:31:35 T:1770091888 WARNING: CPlayerCoreFactory::GetPlayerCore(CHOOSE PLAYER NAME HERE): no such core: CHOOSE PLAYER NAME HERE
16:31:35 T:1770091888 WARNING: Previous line repeats 1 times.
16:31:35 T:1770091888  NOTICE: DVDPlayer: Opening: http://d5500.allmyvideos.net/d/7wmpnhutyq5dh6lnu3eit26rh4cozc5swfrdqx5h7e6t3pehc7ov7cbw5bsuuiq/video.mp4?v2|User-Agent=Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:30.0) Gecko/20100101 Firefox/30.0
16:31:35 T:1770091888 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
16:31:35 T:1877076960  NOTICE: Thread DVDPlayer start, auto delete: false
16:31:35 T:1877076960  NOTICE: Creating InputStream
16:31:36 T:1975590464  NOTICE: Thread FileCache start, auto delete: false
16:31:36 T:1877076960  NOTICE: Creating Demuxer
16:32:06 T:1877076960   ERROR: bool CDVDDemuxFFmpeg::Open(CDVDInputStream*, bool, bool) - Error, could not open file http://d5500.allmyvideos.net/d/7wmpnhutyq5dh6lnu3eit26rh4cozc5swfrdqx5h7e6t3pehc7ov7cbw5bsuuiq/video.mp4?v2
16:32:06 T:1877076960   ERROR: bool CDVDPlayer::OpenDemuxStream() - Error creating demuxer
16:32:06 T:1877076960  NOTICE: CDVDPlayer::OnExit()
16:32:06 T:1770091888   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.live.streamspro/?url=http%3A%2F%2Fallmyvideos.net%2Fqjmuu3bfiz2q&mode=19]
16:32:06 T:1770091888  NOTICE: CDVDPlayer::CloseFile()
16:32:06 T:1770091888  NOTICE: DVDPlayer: waiting for threads to exit
16:32:06 T:1770091888  NOTICE: DVDPlayer: finished waiting
16:32:06 T:1770091888  NOTICE: CDVDPlayer::CloseFile()
16:32:06 T:1770091888  NOTICE: DVDPlayer: waiting for threads to exit
16:32:06 T:1770091888  NOTICE: DVDPlayer: finished waiting
16:32:06 T:1970127128  NOTICE: Thread JobWorker start, auto delete: true
16:34:29 T:1943974832  NOTICE: Thread BackgroundLoader start, auto delete: false
16:34:29 T:1970641864  NOTICE: Thread JobWorker start, auto delete: true

**Comment by tknorris** [comment]
It's what Eldorado already said. XBMC times out after 30 seconds and the site is not responding within that time. In other words, it's got nothing to do with our code and everything to do with the fact that allmyvideos is overloaded and running VERY slow.

**Comment by tknorris** [comment]
I tested a few videos from allmyvideos just now. All of them took between 25 and 45 seconds to start even when using their site in the browser. This is the problem, as Eldorado already said.

**Comment by pikomule** [comment]
What is the solution for Kodi? how to increase the timeout?

**Comment by tknorris** [comment]
You can't. It's hard coded into the Kodi source.

You can try changing "curlclienttimeout" in advancedsettings.xml but my general experience is it won't help because the timeout is taking place waiting on the data to be sent not on the connection attempt.

**Comment by pikomule** [comment]
Thanks, I'll try

**Comment by Eldorados** [comment]
Likely won't work, but there is hope for this to come soon:

http://forum.kodi.tv/showthread.php?tid=221334&highlight=timeout

**Comment by pikomule** [comment]
This resolver works well for allmyvideos, is a modification that made me Livestreams 1.4.1. The problem is that I do not adapt to LSP 1.6.6. You can use this code to work? 

allmyvideos.py:
============

import urllib2
import re

def get_video_url( page_url ):

    # Normaliza la URL
    videoid = re.findall( "http://allmyvideos.net/([a-z0-9A-Z]+)" ,page_url ,flags=re.DOTALL )[0]
    page_url = "http://allmyvideos.net/embed-"+videoid+"-728x400.html"

    headers = {'User-agent' : 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:19.0) Gecko/20100101 Firefox/19.0'}
    req = urllib2.Request(page_url,None,headers)
    res = urllib2.urlopen(req)
    data = res.read()
    res.close()

    # Extrae la URL
    video_url = re.findall( '"sources" : \[.*?"file" : "(.+?\?v2)",' ,data ,flags=re.DOTALL )[0]+"&direct=false"

    return video_url

**Comment by tknorris** [comment]
That code is already in urlresolver.

**Comment by pikomule** [comment]
with this address if it works allmyvideos in LSP 1.4.1. Shani gave official support LSP video servers, but allmyvideos no charge. What is the difference between this and the Eldorados solve? can be adapted?

**Comment by tknorris** [comment]
As Eldorado already explained, the problem is not the code, It's simply allmyvideos is overloaded and times out sometimes. There is no code problem here. The link to the video is passed back to Kodi EXACTLY AS IT SHOULD BE, but some times the video times out, sometimes it doesn't. There is no code change to be made here.

**Comment by pikomule** [comment]
ok, thanks
