### ISSUE TITLE
cloudy.ec not working

### ISSUE THREAD

**Issue by buggsbunny4** [Eldorados/script.module.urlresolver#284]
cloudy.ec urlresolver not working. I am always getting File not found or removed. Can it be fixed.

Thanks in Advance

**Comment by Eldorados** [comment]
Are you sure the file isn't actually removed?Check some links manually and post a log file                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: buggsbunny4Sent: Tuesday, March 31, 2015 10:14 PMTo: Eldorados/script.module.urlresolverReply To: Eldorados/script.module.urlresolverSubject: [script.module.urlresolver] cloudy.ec not working (#284)cloudy.ec urlresolver not working. I am always getting File not found or removed. Can it be fixed.

Thanks in Advance

—Reply to this email directly or view it on GitHub.

**Comment by buggsbunny4** [comment]
No, the file is not removed. See the log file for reference.

21:18:36 T:6772  NOTICE: https://www.cloudy.ec/embed.php?id=121f9971a6ff4
21:18:36 T:6772  NOTICE: URLResolver: Initializing URLResolver version: 2.8.0
21:18:36 T:6772  NOTICE: firsttube.play hosted_media_file={'url': 'https://www.cloudy.ec/embed.php?id=121f9971a6ff4', 'host': '', 'media_id': ''}
21:18:36 T:6772  NOTICE: firsttube.play media_url=True
21:18:36 T:3116  NOTICE: Thread BackgroundLoader start, auto delete: false
21:18:37 T:7604  NOTICE: Thread LanguageInvoker start, auto delete: false
21:18:38 T:7604  NOTICE: -->Python Interpreter Initialized<--
21:18:38 T:7604  NOTICE: firsttube.run
21:18:39 T:6560  NOTICE: DVDPlayer: Opening: https://www.cloudy.ec/embed.php?id=121f9971a6ff4
21:18:39 T:6560 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
21:18:39 T:6560  NOTICE: DXVA::CProcessorHD::PreInit - The Direct3d device doesn't support DXVA-HD.
21:18:39 T:6560  NOTICE: CWinRenderer::Preinit - could not init DXVA-HD processor - skipping
21:18:39 T:8144  NOTICE: Thread DVDPlayer start, auto delete: false
21:18:39 T:8144  NOTICE: Creating InputStream
21:18:40 T:8144  NOTICE: Creating Demuxer
21:18:40 T:3560  NOTICE: Thread FileCache start, auto delete: false
21:18:40 T:8144   ERROR: CDVDDemuxFFmpeg::Open - error probing input format, https://www.cloudy.ec/embed.php?id=121f9971a6ff4
21:18:40 T:8144   ERROR: CDVDPlayer::OpenDemuxStream - Error creating demuxer
21:18:40 T:8144  NOTICE: CDVDPlayer::OnExit()
21:18:40 T:6560   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.firsttube/?action=playable&title=Play+this+video+from+Cloudy&url=https%3A%2F%2Fwww.cloudy.ec%2Fembed.php%3Fid%3D121f9971a6ff4&thumbnail=&plot=&extra=&page=]
21:18:40 T:6560  NOTICE: CDVDPlayer::CloseFile()
21:18:40 T:6560  NOTICE: DVDPlayer: waiting for threads to exit
21:18:40 T:6560  NOTICE: DVDPlayer: finished waiting
21:18:40 T:6560  NOTICE: CDVDPlayer::CloseFile()
21:18:40 T:6560  NOTICE: DVDPlayer: waiting for threads to exit
21:18:40 T:6560  NOTICE: DVDPlayer: finished waiting
21:18:40 T:3692  NOTICE: 1Channel: Service: Playback Stopped
21:18:40 T:3692  NOTICE: 1Channel: Service: Resetting...
21:18:43 T:7516  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by Eldorados** [comment]
This doesn't show the file being reported as deleted, it actually resolves
it but either it's not resolving correctly or the addon you are using is
using urlresolver wrong, the url it's passing to dvdplayer is the same link
it sent in to urlresolver which isn't right

Do you have debugging turned on?

**Comment by buggsbunny4** [comment]
I did turn on the debugging. I think I provided you with the wrong log file. Here is the correct log file and as you can see it says the url is unresolvable.

21:36:39 T:8884  NOTICE: Thread BackgroundLoader start, auto delete: false
21:36:58 T:8072  NOTICE: Thread LanguageInvoker start, auto delete: false
21:36:59 T:8072  NOTICE: -->Python Interpreter Initialized<--
21:37:38 T:8072  NOTICE: firsttube.run
21:37:38 T:8072  NOTICE: firsttube.single_movie {'plot': '', 'title': 'Dolly Ki Doli (2015) Hindi Full Movie  -  DVD', 'url': 'http://firsttube.co/dolly-ki-doli-2015-hindi-full-movie-watch-online-dvd/', 'extra': '', 'page': '', 'action': 'single_movie', 'thumbnail': 'http://firsttube.co/wp-content/uploads/2015/03/Dolly-Ki-Doli-2015-228x160.jpg'}
21:37:38 T:8072  NOTICE: firsttube.read_body_and_headers url=http://firsttube.co/dolly-ki-doli-2015-hindi-full-movie-watch-online-dvd/
21:37:38 T:8072  NOTICE: firsttube.read_body_and_headers only english
21:38:02 T:8072  NOTICE: firsttube.read_body_and_headers url=http://playtube.us/cl.php?v=121f9971a6ff4
21:38:02 T:8072  NOTICE: firsttube.read_body_and_headers only english
21:38:57 T:7708  NOTICE: Thread BackgroundLoader start, auto delete: false
21:39:07 T:6844  NOTICE: Thread LanguageInvoker start, auto delete: false
21:39:08 T:6844  NOTICE: -->Python Interpreter Initialized<--
21:39:14 T:6844  NOTICE: firsttube.run
21:39:14 T:6844  NOTICE: firsttube.play {'plot': '', 'title': 'Video published at cloudy', 'url': 'https://www.cloudy.ec/embed.php?id=121f9971a6ff4', 'extra': '', 'page': '', 'action': 'play', 'thumbnail': ''}
21:41:34 T:6844  NOTICE: url:
21:41:34 T:6844  NOTICE: https://www.cloudy.ec/embed.php?id=121f9971a6ff4
21:41:34 T:6844  NOTICE: URLResolver: Initializing URLResolver version: 2.8.0
21:41:47 T:6844  NOTICE: firsttube.play hosted_media_file={'url': 'https://www.cloudy.ec/embed.php?id=121f9971a6ff4', 'host': '', 'media_id': ''}
21:41:52 T:6844  NOTICE: URLResolver: **** Cloudy Error occured: File Not Found or removed
21:41:55 T:6844  NOTICE: firsttube.play media_url=<urlresolver.plugnplay.interfaces.unresolvable instance at 0x113567B0>
21:41:55 T:7772  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by buggsbunny4** [comment]
21:41:55 T:6844  NOTICE: firsttube.play media_url=urlresolver.plugnplay.interfaces.unresolvable instance at 0x113567B0
21:41:55 T:7772  NOTICE: Thread BackgroundLoader start, auto delete: false
