### ISSUE TITLE
filenuke does not work

### ISSUE THREAD

**Issue by AiWABR** [Eldorados/script.module.urlresolver#290]
filenuke does not work at a time, would solve this problem?

**Comment by Eldorados** [comment]
Need a LOT more info than this                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: AiWABRSent: Sunday, April 19, 2015 9:30 AMTo: Eldorados/script.module.urlresolverReply To: Eldorados/script.module.urlresolverSubject: [script.module.urlresolver] filenuke does not work (#290)filenuke does not work at a time, would solve this problem?

—Reply to this email directly or view it on GitHub.
