### ISSUE TITLE
PureVid settings issue

### ISSUE THREAD

**Issue by Lithium73** [Eldorados/script.module.urlresolver#305]
Hi !
There is a problem into settings saving. Currently, purevid's login and password aren't saved. 
To fix this problem, yoou have to respect urlresolver standard 'id name'. 
Here is the fix into purevid.py : 
 def get_settings_xml(self):
        xml = PluginSettings.get_settings_xml(self)
        xml += '<setting id="PurevidResolver_login" '
        xml += 'type="bool" label="Login" default="false"/>\n'
        xml += '<setting id="PurevidResolverusername" enable="eq(-1,true)" '
        xml += 'type="text" label="     username" default=""/>\n'
        xml += '<setting id="PurevidResolverpassword" enable="eq(-2,true)" '
        xml += 'type="text" label="     password" option="hidden" default=""/>\n'
        xml += '<setting label="Video quality" id="%s_quality" ' % self.__class__.__name__
        xml += 'type="enum" values="FLV|Maximum" default="0" />\n'
        xml += '<setting label="This plugin calls the Purevid urlresolver - '
        xml += 'change settings there." type="lsep" />\n'
        return xml
Thanks in advance !

**Comment by JUL1EN094** [comment]
Hi,

Sorry but I don't agree :( . The original code works well for me and all of my users (several thousands). i checked just now and modifications in purevid urlresolver settings (username,..) are saved properly. 
And so I don't understand one other think : you talked about respect urlresolver standard 'id name', but there is no 'id name' in the get_settings_xml function you above offers ??

**Comment by Eldorados** [comment]
I have to agree with JU1EN094, current code seems to be working fine for me
as well

**Comment by Lithium73** [comment]
Hi, 

My bad... I'm on an old version of urlresolver (getted from an old repo, i'm totally sorry)... the version on git repo is good. Have a good day ;-)

**Comment by JUL1EN094** [comment]
OK. So could you close the issue ? thanks
