### ISSUE TITLE
Causing Kodi to crash under OSX 10.6 and 10.7, Kodi 14.1, 15.2 and 16.0

### ISSUE THREAD

**Issue by s7ntax** [Eldorados/script.module.urlresolver#369]
This module was updated 2 days ago and since it was modified Kodi crashes on launch under OSX, until I delete the module from Addons under Application support. Without it Dubstop and other addons will not resolve URLs but with it Kodi crashes and burns on launch.

Crash log data

[http://pastebin.com/mcckFw2Z](url)

It seems to be 2.10.13~beta3 that is causing the issue.

**Comment by Eldorados** [comment]
Sorry crash log doesn't tell me anything, would need to see the regular log
file

Not sure how it could cause Kodi to crash on startup as the script isn't
active until an addon calls it

**Comment by tknorris** [comment]
If you update to beta6, this should be fixed.

**Comment by s7ntax** [comment]
Thanks, for some reason I was only getting beta3 with auto updates but I've updated from tknorris repo and all seems well.
